/**
 * Native implementation of LivePreviewInput.
 *
 * Hosts the same CodeMirror 6 Live Preview editor as the web build, but inside
 * a react-native-webview instead of an <iframe>. The HTML is generated by
 * `buildEditorHtml()` — the single source of truth for editor visuals shared
 * between web and native.
 *
 * Host → WebView messages (injected via injectJavaScript → window.postMessage):
 *   { type: 'set-value', value: string }
 *   { type: 'apply-format', command: string }
 *   { type: 'focus' }
 *   { type: 'set-readonly', readonly: boolean }
 *
 * WebView → Host messages (via window.ReactNativeWebView.postMessage):
 *   { type: 'ready' }
 *   { type: 'change', value: string }
 *   { type: 'active-formats', formats: string[] }
 *   { type: 'height', height: number }
 *   { type: 'command-applied' }
 *   { type: 'error', message: string }
 */
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { View, StyleSheet } from 'react-native';
import { WebView, type WebViewMessageEvent } from 'react-native-webview';
import { buildEditorHtml } from './live-preview/editorHtml';
import type { FormatCommand } from './types';

interface LivePreviewInputProps {
  value: string;
  onChange: (text: string) => void;
  inputMode?: 'ink' | 'scroll';
  placeholder?: string;
  onFocus?: () => void;
  pendingCommand?: FormatCommand | null;
  onCommandApplied?: () => void;
  onActiveFormatsChange?: (formats: FormatCommand[]) => void;
  autoFocus?: boolean;
  focusKey?: string | null;
}

/**
 * Injected script that rewires the iframe's `postMessage` bridge so the
 * CodeMirror host code (which uses `window.parent.postMessage` and a
 * `message` listener on the inner window) talks to the React Native side
 * via `window.ReactNativeWebView.postMessage` instead.
 *
 * The shared editorHtml.ts uses:
 *   - `window.parent.postMessage(msg, '*')` to notify the host
 *   - `window.addEventListener('message', handler)` to receive host messages
 *
 * On native there is no real parent frame, so we shim both sides.
 */
const BRIDGE_SHIM = `
(function() {
  if (window.__graphiteBridgeInstalled) return;
  window.__graphiteBridgeInstalled = true;

  // Outbound: redirect window.parent.postMessage -> ReactNativeWebView
  try {
    var rn = window.ReactNativeWebView;
    var fakeParent = {
      postMessage: function(msg) {
        try {
          rn.postMessage(typeof msg === 'string' ? msg : JSON.stringify(msg));
        } catch (e) {
          rn.postMessage(JSON.stringify({ type: 'error', message: String(e) }));
        }
      }
    };
    try { Object.defineProperty(window, 'parent', { value: fakeParent, configurable: true }); } catch (e) {}
    try { Object.defineProperty(window, 'top',    { value: fakeParent, configurable: true }); } catch (e) {}
  } catch (e) {
    window.ReactNativeWebView.postMessage(JSON.stringify({ type: 'error', message: 'bridge-install:' + String(e) }));
  }

  // Surface runtime errors to the host
  window.addEventListener('error', function(e) {
    try {
      window.ReactNativeWebView.postMessage(JSON.stringify({
        type: 'error',
        message: (e && e.message) ? e.message : 'unknown',
      }));
    } catch (_) {}
  });

  true;
})();
true;
`;

export function LivePreviewInput({
  value,
  onChange,
  inputMode = 'scroll',
  onFocus,
  pendingCommand,
  onCommandApplied,
  onActiveFormatsChange,
  autoFocus = false,
  focusKey = null,
}: LivePreviewInputProps) {
  const webViewRef = useRef<WebView>(null);
  const readyRef = useRef(false);
  const [contentHeight, setContentHeight] = useState<number>(500);

  // Refs to latest prop values — same pattern as the web component, needed so
  // the `ready` handler seeds the editor with the CURRENT value rather than
  // the value captured at mount time.
  const valueRef = useRef(value);
  const onChangeRef = useRef(onChange);
  const onFocusRef = useRef(onFocus);
  const onCommandAppliedRef = useRef(onCommandApplied);
  const onActiveFormatsChangeRef = useRef(onActiveFormatsChange);
  const autoFocusRef = useRef(autoFocus);
  const inputModeRef = useRef(inputMode);
  useEffect(() => { valueRef.current = value; }, [value]);
  useEffect(() => { onChangeRef.current = onChange; }, [onChange]);
  useEffect(() => { onFocusRef.current = onFocus; }, [onFocus]);
  useEffect(() => { onCommandAppliedRef.current = onCommandApplied; }, [onCommandApplied]);
  useEffect(() => { onActiveFormatsChangeRef.current = onActiveFormatsChange; }, [onActiveFormatsChange]);
  useEffect(() => { autoFocusRef.current = autoFocus; }, [autoFocus]);
  useEffect(() => { inputModeRef.current = inputMode; }, [inputMode]);

  // Last value pushed into the WebView — used to dedupe echoes from `change`
  const lastSentValueRef = useRef('');

  // Build the HTML once per mount
  const html = useMemo(() => buildEditorHtml(), []);

  function postToFrame(msg: object) {
    const js = `
      (function() {
        try {
          window.dispatchEvent(new MessageEvent('message', { data: ${JSON.stringify(msg)} }));
        } catch (e) {
          window.ReactNativeWebView.postMessage(JSON.stringify({ type: 'error', message: 'post:' + String(e) }));
        }
      })();
      true;
    `;
    webViewRef.current?.injectJavaScript(js);
  }

  function handleMessage(e: WebViewMessageEvent) {
    let msg: { type: string; [k: string]: any };
    try {
      msg = JSON.parse(e.nativeEvent.data);
    } catch {
      return;
    }
    if (!msg?.type) return;

    switch (msg.type) {
      case 'ready': {
        readyRef.current = true;
        const initValue = valueRef.current ?? '';
        lastSentValueRef.current = initValue;
        postToFrame({ type: 'set-value', value: initValue });
        postToFrame({ type: 'set-readonly', readonly: inputModeRef.current === 'ink' });
        if (autoFocusRef.current) postToFrame({ type: 'focus' });
        break;
      }

      case 'change':
        if (msg.value !== lastSentValueRef.current) {
          lastSentValueRef.current = msg.value as string;
          onChangeRef.current(msg.value as string);
        }
        break;

      case 'active-formats':
        onActiveFormatsChangeRef.current?.(msg.formats as FormatCommand[]);
        break;

      case 'height':
        if (typeof msg.height === 'number' && msg.height > 0) {
          setContentHeight(msg.height);
        }
        break;

      case 'command-applied':
        onCommandAppliedRef.current?.();
        break;

      case 'error':
        // Surface WebView errors so they don't disappear silently in release
        // builds. Wrapped in a conditional so dev-only console usage does not
        // ship as a production log.
        // Surface WebView errors in dev only — guarded via the RN __DEV__
        // global which is always defined at runtime on native.
        if (typeof (globalThis as any).__DEV__ !== 'undefined' && (globalThis as any).__DEV__) {
          // eslint-disable-next-line no-console
          console.warn('[LivePreviewInput.native] WebView error:', msg.message);
        }
        break;
    }
  }

  // Sync value → WebView when prop changes from above
  useEffect(() => {
    if (!readyRef.current) return;
    if (value !== lastSentValueRef.current) {
      lastSentValueRef.current = value;
      postToFrame({ type: 'set-value', value });
    }
  }, [value]);

  // Sync inputMode → readonly
  useEffect(() => {
    if (!readyRef.current) return;
    postToFrame({ type: 'set-readonly', readonly: inputMode === 'ink' });
  }, [inputMode]);

  useEffect(() => {
    if (!readyRef.current || !focusKey || inputMode === 'ink') return;
    postToFrame({ type: 'focus' });
  }, [focusKey, inputMode]);

  // Apply format commands from the toolbar
  useEffect(() => {
    if (!pendingCommand) return;
    if (!readyRef.current) {
      onCommandAppliedRef.current?.();
      return;
    }
    postToFrame({ type: 'apply-format', command: pendingCommand });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pendingCommand]);

  // Apple Pencil / ink mode: when inputMode === 'ink', the Skia layer above
  // must own all touches. We disable pointer events on the WebView wrapper so
  // pan/draw gestures pass through to the InkLayer sibling rendered on top.
  const inkMode = inputMode === 'ink';

  return (
    <View
      style={[styles.container, { height: Math.max(contentHeight, 500) }]}
      pointerEvents={inkMode ? 'none' : 'auto'}
      onTouchStart={() => {
        if (!inkMode) onFocusRef.current?.();
      }}
    >
      <WebView
        ref={webViewRef}
        originWhitelist={['*']}
        source={{ html }}
        javaScriptEnabled
        domStorageEnabled
        injectedJavaScriptBeforeContentLoaded={BRIDGE_SHIM}
        onMessage={handleMessage}
        scrollEnabled={false}
        hideKeyboardAccessoryView
        keyboardDisplayRequiresUserAction={false}
        automaticallyAdjustContentInsets={false}
        showsVerticalScrollIndicator={false}
        showsHorizontalScrollIndicator={false}
        style={styles.webView}
        containerStyle={styles.webViewContainer}
        // Critical for transparency so the canvas bgBase shows through
        // any margins CodeMirror doesn't paint.
        androidLayerType="hardware"
        opaque={false}
        backgroundColor="transparent"
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    width: '100%',
    flexGrow: 1,
  },
  webView: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  webViewContainer: {
    backgroundColor: 'transparent',
  },
});
